export const scenes = [
  {
    title: "Global View",
    description: "The Global Semiconductor Supply Chain",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Stages Overview",
    description: "Three stages of the semiconductor value chain",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Design Stage",
    description: "First stage: Design",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Global View 6",
    description: "Section 6",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "IC Design Revenue Share",
    description: "Global IC design revenue by country, 2021",
    center: [20, 28],
    zoom: 1.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "California Fabless Cluster",
    description: "Zoom into California fabless companies",
    center: [-119.5, 36.2],
    zoom: 5.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Bay Area EDA & IP",
    description: "Zoom into Synopsys and Cadence in the Bay Area",
    center: [-121.95, 37.4],
    zoom: 8.6,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "US IDM Cluster",
    description: "Zoom into key American IDMs",
    center: [-97, 39],
    zoom: 4.1,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Asia IDM & Fabless Cluster",
    description: "Zoom into key Asian IDMs and fabless designers",
    center: [120, 35],
    zoom: 4.2,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Europe EDA & IDM Cluster",
    description: "Zoom into key European EDA/IP and IDM players",
    center: [8, 51],
    zoom: 4.2,
    pitch: 0,
    bearing: 0,
  },
];

