export const scenes = [
  {
    title: "Global View",
    description: "The Global Semiconductor Supply Chain",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Stages Overview",
    description: "Three stages of the semiconductor value chain",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Design Stage",
    description: "First stage: Design",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Global View 6",
    description: "Section 6",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "IC Design Revenue Share",
    description: "Global IC design revenue by country, 2021",
    center: [20, 28],
    zoom: 1.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "California Fabless Cluster",
    description: "Zoom into California fabless companies",
    center: [-119.5, 36.2],
    zoom: 5.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Bay Area EDA & IP",
    description: "Zoom into Synopsys and Cadence in the Bay Area",
    center: [-121.95, 37.4],
    zoom: 8.6,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "US IDM Cluster",
    description: "Zoom into key American IDMs",
    center: [-97, 39],
    zoom: 4.1,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Asia IDM & Fabless Cluster",
    description: "Zoom into key Asian IDMs and fabless designers",
    center: [120, 35],
    zoom: 4.2,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Europe EDA & IDM Cluster",
    description: "Zoom into key European EDA/IP and IDM players",
    center: [8, 51],
    zoom: 4.2,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Manufacturing Overview",
    description: "Manufacturing stage overview",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Manufacturing Inputs",
    description: "Manufacturing inputs and equipment",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Manufacturing Business Models",
    description: "Pure-play foundry vs IDM",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Advanced Processes Market Share",
    description: "Advanced process node market share 2024",
    center: [20, 28],
    zoom: 1.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Mature Processes Market Share",
    description: "Mature process node market share 2024",
    center: [20, 28],
    zoom: 1.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "",
    description: "",
    center: [20, 28],
    zoom: 1.8,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "",
    description: "",
    center: [165, 36],
    zoom: 2.3,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "",
    description: "",
    center: [-55, 45],
    zoom: 2.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "",
    description: "",
    center: [75, 42],
    zoom: 2.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "ATP Overview",
    description: "Assembly, test, and packaging",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "ATP Inputs",
    description: "ATP inputs and equipment",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "IDM and OSAT",
    description: "ATP business models",
    center: [0, 20],
    zoom: 1.5,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "Global ATP Capacity",
    description: "ATP capacity by region",
    center: [0, 5],
    zoom: 1.7,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "OSAT Taiwan",
    description: "Key OSAT companies in Taiwan",
    center: [122.85, 23.25],
    zoom: 6.55,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "OSAT China",
    description: "Key OSAT companies in China",
    center: [78.5, 35.5],
    zoom: 2.95,
    pitch: 0,
    bearing: 0,
  },
  {
    title: "OSAT Global",
    description: "OSAT companies US, Japan, Korea",
    center: [12, 28],
    zoom: 1.7,
    pitch: 0,
    bearing: 0,
  },
];

